apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  # Headless ServiceにすることでIPディスカバリを可能にする
  # そうすることで書き込み専用、読み込み専用のPodを指定して接続できる
  clusterIP: None
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
