apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/mysql
  - ../../base/redis
  - ../../base/learning-product-service

patches:
  - target:
      kind: StatefulSet
      name: mysql
    path: mysql-storage-patch.yaml
